version: '3'
services:
  mongodb:
    image: mongo
    container_name: "student_db"
    volumes:
      - student_db_data:/data/db
    ports:
      - "${DB_PORT:-27017}:27017"

  server:
    build: .
    depends_on:
      - "mongodb"
    command: "npm run start:prod"
    container_name: "student_app"
    ports:
      - "${SERVER_PORT:-8005}:8005"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
      - NODE_ENV=production
      - PORT=8005
      - MONGO_NAME=mongodb

volumes:
  student_db_data: